stages:
  - build
  - test

default:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/haskell:9.6

build:
  stage: build
  script:
    - stack build --copy-bins --local-bin-path build
  artifacts:
    paths:
      - build/microc
  rules:
    - when: always

unittest:
  stage: test
  script:
    - stack test
  allow_failure: true
  rules:
    - when: always

test:
  stage: test
  script:
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.fit.cvut.cz/NI-APR/B251/tests.git /tests
    - chmod +x /tests/test.sh
    - /tests/test.sh --microc "build/microc" --suite "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
